### ISSUE TITLE
Documentation of profile and attribute type values

### ISSUE THREAD

**Issue by johannrichard** [tobiasgraf/homeejs#3]
What I'm lacking (and I couldn't find one central reference) is a central collection of all known `profile` and attribute `type` values and what they correspond to (e.g. "Dimmer" or "Bulb", "Door/Window Sensor" etc.).

@tobiasgraf I mainly open this issue as a placeholder and reminder for myself until I 

* Collect the profile and type values in my own `homee` installation
* Create a pull request for a Wiki Page collecting these in an accessible way

**Comment by tobiasgraf** [comment]
Did you have a look here? 
https://github.com/stfnhmplr/homee-api/blob/master/lib/enums.js

**Comment by johannrichard** [comment]
No, haven’t seen that one! I still think a bit more detailed info would be helpful, but then it’s maybe a pill request for the `node-red-contrib-homee`! Thanks a lot for pointing it out.
